/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moyin_cn_tech_recorder_SoundMagicApi */

#ifndef _Included_com_moyin_cn_tech_recorder_SoundMagicApi
#define _Included_com_moyin_cn_tech_recorder_SoundMagicApi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_NORMAL
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_NORMAL 0L
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_LUOLI
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_LUOLI 1L
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_DASHU
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_DASHU 2L
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_JINGSONG
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_JINGSONG 3L
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_GAOGUAI
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_GAOGUAI 4L
#undef com_moyin_cn_tech_recorder_SoundMagicApi_MODE_KONGLING
#define com_moyin_cn_tech_recorder_SoundMagicApi_MODE_KONGLING 5L
/*
 * Class:     com_moyin_cn_tech_recorder_SoundMagicApi
 * Method:    changeSound
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_moyin_cn_tech_recorder_SoundMagicApi_changeSound
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif